### PR TITLE
FD-5939 - Add googleplus provider (include sample)

### PR DESCRIPTION
**Pull request by j-alpajora**
Include googleplus provider.

### CODE REVIEW

**Comment by finder-dp-lewis** [comment]
Was the `workspace.xml` file supposed to be in this PR?

**Comment by j-alpajora** [comment]
Hi @finder-dp-lewis, workspace.xml was removed and package version was also updated.

**Comment by finder-dp-lewis** [comment]
Did the build process create a minified version of the code too?

**Comment by j-alpajora** [comment]
done including minified version, @finder-dp-lewis

**Comment by finder-dp-lewis** [comment]
:+1:

**Pull request merged**
